# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("Server") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "shell", inline: <<-SHELL
     cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
     sudo apt install nodejs -y
     sudo apt install git-all -y
     sudo apt install npm -y

     mkdir server
     cd server
     git clone https://github.com/EstefaSora125/Lab2-SD.git
     cd servidor

     npm install
     npm install pm2 -g

     pm2 start index.js
   SHELL
end
